version: '3.3'
services:
  zookeeper:
    restart: "no"
    image: wurstmeister/zookeeper
    container_name: calit_zookeeper
    ports:
      - "2181:2181"
  kafka:
    restart: "no"
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    container_name: calit_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "calit:1:1,"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
